language: node_js
node_js:
  - node
  - lts/*
install:
  - npm install
before_script:
  - npm rebuild node-sass
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  target_branch:
  on:
    branch: main
    node: 'lts/*'
